### ISSUE TITLE
Add proper left/right delimiters

### ISSUE THREAD

**Issue by fabian-s** [compstat-lmu/latex-math#1]
![image](https://user-images.githubusercontent.com/998541/38603833-fe771228-3d6e-11e8-8ab8-70318169bc03.png)

**Comment by berndbischl** [comment]
kannst du direkt änern wenn du willst

**Comment by fabian-s** [comment]
Ok, mach ich wenn du das auch so siehst.

**Comment by berndbischl** [comment]
jo go

**Comment by berndbischl** [comment]
brauchst du rechte?
