### ISSUE TITLE
Generalization error GE(f_D) is a function of x

### ISSUE THREAD

**Issue by fabian-s** [compstat-lmu/latex-math#3]
.. so it should be $GE(f_D(x))$

**Comment by fabian-s** [comment]
![image](https://user-images.githubusercontent.com/998541/38884140-f4886c30-426e-11e8-85a9-ac3ff2712df5.png)

makes more sense to me than defining this as a functional of the learner. error depends on the input x, through its bias and variance which typically change locally.

**Comment by berndbischl** [comment]
why did you close?

**Comment by berndbischl** [comment]
wir können hier auch deutsch reden.
war das closen ein fehler oder die issue selber?

**Comment by fabian-s** [comment]
.... cause I fixed it ...

**Comment by berndbischl** [comment]
ok, ich finde den fix nicht perfekt, aber ok

**Comment by fabian-s** [comment]
dachte ich informiere dich per issue darüber dass ich es geändert habe falls es doch anders gehört

**Comment by fabian-s** [comment]
wie besser?

**Comment by berndbischl** [comment]
das ist jetzt doof per tippen zu erklären. also GE(fhat) soll der generalization error der funktion fhat sein, ausgewertet auf der verteilung P

**Comment by fabian-s** [comment]
GE(f_D, x)?

**Comment by fabian-s** [comment]
![image](https://user-images.githubusercontent.com/998541/38884576-518177c8-4270-11e8-8b28-f4d686a3b6f3.png)

... so präferiert? Eigenschaft des Modells, aber abhängig von x

**Comment by berndbischl** [comment]
in neuen papers haben wir mal GE(fhat, P) geschrieben. und für den schätzer GE_hat(fhat, D). wobei D eine sauberer testdaten satz aus P sein soll.

lange rede kurzer sind, für mich ist die eingabe von GE, also das math. objekt was ich reinstecke die function fhat. man kann auch sagen, ich schreibe die funktion jetzt als fhat(x), statt fhat (ohne klammern), und worüber ich hier rede ist korinthenkackerei.

darüber wollte ich aber eigentlich mit dem symbol nie reden:

>> error depends on the input x, through its bias and variance which typically change locally.

und das ist auch ein problem, weil für mich ist GE ja genau das *integral* wenn ich über alle x gehe, bzgl P.....

macht das sinn?

**Comment by berndbischl** [comment]
naja, dann wollen wir wohl 2 symbole. eins mit x, und eins wo ich über x integriert habe....

**Comment by berndbischl** [comment]
bist du noch im büro? ich kann noch eine andere sache dazu sagen, aber im chat ist das echt schwierig

**Comment by fabian-s** [comment]
> für mich ist GE ja genau das integral wenn ich über alle x

das ist zumindest nicht das was auf deinen Folien steht....
ich bin grad am aufbrechen, las m,orgen quatschen, ist nicht dringend

**Comment by berndbischl** [comment]
ok. morgen ist janek bei mir zuhause. kannst locker callen. pingst du mich?

**Comment by fabian-s** [comment]
wie besprochen: ursprüngliche Definition bleibt erhalten.
